// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHEuBfjqytHxUwvkMT6om0ZGUdVycPhmo',
    appId: '1:327758991149:web:4c65aa48664b80a1d50da4',
    messagingSenderId: '327758991149',
    projectId: 'anaam-6cd94',
    authDomain: 'anaam-6cd94.firebaseapp.com',
    storageBucket: 'anaam-6cd94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI0PBU3fzVf25EfbW-NgVhgMQuOcXYkRA',
    appId: '1:327758991149:android:27579ccad0f8fa8bd50da4',
    messagingSenderId: '327758991149',
    projectId: 'anaam-6cd94',
    storageBucket: 'anaam-6cd94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRElOPiQ6ezO8efaXi45frPtUr0FJm4dk',
    appId: '1:327758991149:ios:37d43d42ca2d3989d50da4',
    messagingSenderId: '327758991149',
    projectId: 'anaam-6cd94',
    storageBucket: 'anaam-6cd94.appspot.com',
    iosClientId: '327758991149-ea72uo9vnn26ob4vs04etnqk61m5fa5g.apps.googleusercontent.com',
    iosBundleId: 'com.en3am.en3amApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRElOPiQ6ezO8efaXi45frPtUr0FJm4dk',
    appId: '1:327758991149:ios:37d43d42ca2d3989d50da4',
    messagingSenderId: '327758991149',
    projectId: 'anaam-6cd94',
    storageBucket: 'anaam-6cd94.appspot.com',
    iosClientId: '327758991149-ea72uo9vnn26ob4vs04etnqk61m5fa5g.apps.googleusercontent.com',
    iosBundleId: 'com.en3am.en3amApp',
  );
}
